services:
  wolframalpha:
    image: mgultra
    build:
      context: .
      dockerfile: src/DiscordClient/Dockerfile
    container_name: mgultra
    env_file:
      - .env
    shm_size: 256mb
    restart: unless-stopped
    depends_on:
      - credentials